### ISSUE TITLE
KeyError: 'APP_SETTINGS' while upgrading / testing the server

### ISSUE THREAD

**Issue by jay-thakur** [intuinno/conceptvector#18]
Hi,

I have cloned this repo & trying to setup on my windows machine.

I have created the `env_vars.sh` file. & added the given content. But when I run `python manage.py runserver`, getting following error.

![image](https://user-images.githubusercontent.com/2772085/117522455-1a2d1d80-af79-11eb-9a33-8331013b4237.png)

@Shadek07 Could you please help me, where am I doing wrong or missing anything.

Thanks,
Jay

**Comment by thadguidry** [comment]
Hi Jay! (long time no see...lolol...hope school is going OK!)

Set your env variables in Windows 10 by clicking in the search box next to your Windows start and typing "env" then choose Edit environment settings for your account.  Like so:
![image](https://user-images.githubusercontent.com/986438/117522897-6a0ce400-af7b-11eb-8682-efee54dab199.png)

Then set whatever the application or program needs...in the top half are the User variables, and by clicking on NEW or Edit if you already have the variable set and need to just modify it.
![image](https://user-images.githubusercontent.com/986438/117522959-d25bc580-af7b-11eb-90de-41d7177dcbfb.png)

In this case, in the Conceptvector README.md further down you can read that
you need to have a variable called
`APP_SETTINGS` 
it needs to have a value of
`config.DevelopmentConfig`
and the same for 
`DATABASE_URL`
with a value of
`postgresql://postgres:postgres@localhost/conceptvectorDB`

**Comment by jay-thakur** [comment]
Hi @thadguidry,

thanks man. I am doing good. yes, school is going fine.

I got you. we need to set user variable in system environment path. 

But I would like to know, since we are setting these config variable in anaconda conceptvector environment like this 

![image](https://user-images.githubusercontent.com/2772085/117527756-f62b0580-af93-11eb-9c46-9705040f6327.png)

 then why do we need to add these variables in environment variable again? shouldn't it take from anaconda environment ?
 
 Thanks,
Jay

**Comment by thadguidry** [comment]
The .sh files are shell scripts which are Linux and not .bat files on Windows.  Unless you are running the whole stack in WSL (or Docker) than the .sh files are not being run.
