### ISSUE TITLE
Understanding dataset

### ISSUE THREAD

**Issue by jay-thakur** [intuinno/conceptvector#22]
Hi,

I have downloaded dataset from [here](http://nlp.stanford.edu/data/glove.6B.zip).

But when I unzip, its like this - 
![image](https://user-images.githubusercontent.com/2772085/119710318-d31da400-be23-11eb-9c74-c8170145dd63.png)

But in code, we are using -

![image](https://user-images.githubusercontent.com/2772085/119710440-fb0d0780-be23-11eb-9d2b-2280e1f5268c.png)

So, I changed the downloaded file name to `"wiki_4gram_50d.txt"` But I was getting error.

So I changed the encoding like this - 
![image](https://user-images.githubusercontent.com/2772085/119711519-41af3180-be25-11eb-9bda-b1623a62a6af.png)

It works fine.

But Wanted to know, Am I using the correct dataset ? or need to use other dataset ?

@Shadek07 please guide.

Thanks,
Jay

**Comment by Shadek07** [comment]
Are you working on conceptvector or EssayIQ project? The globe data has been used for conceptvector project, not for EssayIQ. The "wiki_4gram_50d.txt" dataset you have to create by 4 steps process mentioned here https://github.com/Shadek07/EssayIQ/tree/master/word2vec_for_phrase

**Comment by jay-thakur** [comment]
working on EssayIQ.

Got it. 

Thank you so much.
